services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    user: "0:0"
    ports:
      - "5001:5000"
    environment:
      LT_LOAD_ONLY: "en,ko"
      LT_PRELOAD: "true"
      LT_UPDATE_MODELS: "true"
    command: ["--host", "0.0.0.0", "--port", "5000"]
    volumes:
      - lt_models:/home/libretranslate/.local/share/argos-translate
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/languages | grep -q '\"code\":\"ko\"' && grep -q '\"code\":\"en\"'"]
      interval: 20s
      timeout: 5s
      retries: 10

  spacy-api:
    build:
      context: ./spacy-api
    container_name: spacy-api
    restart: unless-stopped
    volumes:
      - ./spacy-api:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  fastapi-api:
    build:
      context: ./fastapi-api
    container_name: fastapi-api
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  zookeeper:
    image: bitnamilegacy/zookeeper:3.9 #Bitnami가 기존 버전 이미지를 bitnamilegacy 저장소로 옮겼습니다
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net

  kafka:
    image: bitnamilegacy/kafka:3.7 #Bitnami가 기존 버전 이미지를 bitnamilegacy 저장소로 옮겼습니다.
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - kafka-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - kafka-net

volumes:
  pgdata:
  redisdata:
  lt_models:
  grafana-data:   # 여기 빠져서 에러났던 것!

networks:
  kafka-net:
